# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Envject < Formula
  desc ""
  homepage "https://github.com/michaelhenry/homebrew-envject"
  version "2.0.0"

  on_macos do
    url "https://github.com/michaelhenry/envject/releases/download/v2.0.0/envject_2.0.0_darwin_all.tar.gz"
    sha256 "b00c8c09bf9706d37bc2556a7812f2786652229c789685976e3f71689ccfadce"

    def install
      bin.install "envject"
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/michaelhenry/envject/releases/download/v2.0.0/envject_2.0.0_linux_arm64.tar.gz"
      sha256 "e6ffbb701788478116ab78aa83843a64dbe905ca8bdf9be92385a443f433d6ab"

      def install
        bin.install "envject"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/michaelhenry/envject/releases/download/v2.0.0/envject_2.0.0_linux_amd64.tar.gz"
      sha256 "53fb1609578a51ddfa5d6990183fb2e8e66d8858748ce64bec1ad04f9afa2c4e"

      def install
        bin.install "envject"
      end
    end
  end
end
