# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Envject < Formula
  desc ""
  homepage "https://github.com/michaelhenry/homebrew-envject"
  version "2.0.0-beta"

  on_macos do
    url "https://github.com/michaelhenry/envject/releases/download/v2.0.0-beta/envject_2.0.0-beta_darwin_all.tar.gz"
    sha256 "821aac692cb563667bc4e89d7eac525e3fe3b5b364c0679c25e45910c83b64e5"

    def install
      bin.install "envject"
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/michaelhenry/envject/releases/download/v2.0.0-beta/envject_2.0.0-beta_linux_arm64.tar.gz"
      sha256 "1851c209b6254c2db19d56fb892d2ddc0f16bcc69a620cd9139308a57d8cda54"

      def install
        bin.install "envject"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/michaelhenry/envject/releases/download/v2.0.0-beta/envject_2.0.0-beta_linux_amd64.tar.gz"
      sha256 "59c2b2e91a7c25deea35dcec7f48f3d9871ddd9ca7a9e16f1ac32a2219364b51"

      def install
        bin.install "envject"
      end
    end
  end
end
