# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Envject < Formula
  desc ""
  homepage "https://github.com/michaelhenry/homebrew-envject"
  version "0.0.1"

  on_macos do
    url "https://github.com/michaelhenry/envject/releases/download/v0.0.1/envject_0.0.1_darwin_all.tar.gz"
    sha256 "c662ee9cbf318627f9c8d48ec77f0613aa34cb61428f9b75c579daa3d492fe6f"

    def install
      bin.install "envject"
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/michaelhenry/envject/releases/download/v0.0.1/envject_0.0.1_linux_arm64.tar.gz"
      sha256 "77bc8dcbc1d007f319439b5b57bc41278dee7537308c25053b11c9160d700d68"

      def install
        bin.install "envject"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/michaelhenry/envject/releases/download/v0.0.1/envject_0.0.1_linux_amd64.tar.gz"
      sha256 "a8f17b79d9f2249ebaa03f3f587af1b3cb20432a6fe6d110ba459b3a9f42bd4b"

      def install
        bin.install "envject"
      end
    end
  end
end
